# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_cluster_coef_r <- function(family, nb_coef, theta, diffMax_NR, r_mu, r_lhs, r_sum_y, r_dum, r_obsCluster, r_table, r_cumtable, nthreads) {
    .Call(`_fixest_compute_cluster_coef_r`, family, nb_coef, theta, diffMax_NR, r_mu, r_lhs, r_sum_y, r_dum, r_obsCluster, r_table, r_cumtable, nthreads)
}

update_mu_single_cluster <- function(family, nb_cluster, theta, diffMax_NR, mu_in, lhs, sum_y, dum, obsCluster, table, cumtable, nthreads) {
    .Call(`_fixest_update_mu_single_cluster`, family, nb_cluster, theta, diffMax_NR, mu_in, lhs, sum_y, dum, obsCluster, table, cumtable, nthreads)
}

cpp_conv_acc_gnl <- function(family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads) {
    .Call(`_fixest_cpp_conv_acc_gnl`, family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads)
}

cpp_conv_seq_gnl <- function(family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads) {
    .Call(`_fixest_cpp_conv_seq_gnl`, family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads)
}

get_n_cells <- function(index_i, index_j) {
    .Call(`_fixest_get_n_cells`, index_i, index_j)
}

cpp_conv_acc_poi_2 <- function(n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order) {
    .Call(`_fixest_cpp_conv_acc_poi_2`, n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order)
}

cpp_conv_seq_poi_2 <- function(n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order) {
    .Call(`_fixest_cpp_conv_seq_poi_2`, n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order)
}

cpp_fixed_cost_gaussian <- function(n_i, n_cells, index_i, index_j, order, invTableCluster_vector, dum_vector) {
    .Call(`_fixest_cpp_fixed_cost_gaussian`, n_i, n_cells, index_i, index_j, order, invTableCluster_vector, dum_vector)
}

cpp_conv_acc_gau_2 <- function(n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in) {
    .Call(`_fixest_cpp_conv_acc_gau_2`, n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in)
}

cpp_conv_seq_gau_2 <- function(n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in) {
    .Call(`_fixest_cpp_conv_seq_gau_2`, n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in)
}

cpp_derivconv_seq_gnl <- function(iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector) {
    .Call(`_fixest_cpp_derivconv_seq_gnl`, iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector)
}

cpp_derivconv_acc_gnl <- function(iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector) {
    .Call(`_fixest_cpp_derivconv_acc_gnl`, iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector)
}

cpp_derivconv_acc_2 <- function(iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, ll_d2, order, jacob_vector, deriv_init_vector, dum_vector) {
    .Call(`_fixest_cpp_derivconv_acc_2`, iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, ll_d2, order, jacob_vector, deriv_init_vector, dum_vector)
}

cpp_derivconv_seq_2 <- function(iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, order, ll_d2, jacob_vector, deriv_init_vector, dum_vector) {
    .Call(`_fixest_cpp_derivconv_seq_2`, iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, order, ll_d2, jacob_vector, deriv_init_vector, dum_vector)
}

update_deriv_single <- function(n_vars, nb_coef, r_ll_d2, r_jacob_vector, r_dum_vector) {
    .Call(`_fixest_update_deriv_single`, n_vars, nb_coef, r_ll_d2, r_jacob_vector, r_dum_vector)
}

cpp_demean <- function(y, X_raw, r_weights, iterMax, diffMax, r_nb_id_Q, fe_id_list, table_id_I, slope_flag_Q, slope_vars_list, r_init, nthreads, save_fixef = FALSE) {
    .Call(`_fixest_cpp_demean`, y, X_raw, r_weights, iterMax, diffMax, r_nb_id_Q, fe_id_list, table_id_I, slope_flag_Q, slope_vars_list, r_init, nthreads, save_fixef)
}

cpp_which_na_inf <- function(x, nthreads) {
    .Call(`_fixest_cpp_which_na_inf`, x, nthreads)
}

cpp_cholesky <- function(X, tol = 1.0/100000.0/100000.0, nthreads = 1L) {
    .Call(`_fixest_cpp_cholesky`, X, tol, nthreads)
}

cpp_sparse_products <- function(X, w, y, correct_0w = FALSE, nthreads = 1L) {
    .Call(`_fixest_cpp_sparse_products`, X, w, y, correct_0w, nthreads)
}

cpppar_crossprod <- function(X, w, nthreads) {
    .Call(`_fixest_cpppar_crossprod`, X, w, nthreads)
}

cpp_mat_reconstruct <- function(X, id_excl) {
    .Call(`_fixest_cpp_mat_reconstruct`, X, id_excl)
}

cpp_iv_products <- function(X, y, Z, u, w, nthreads) {
    .Call(`_fixest_cpp_iv_products`, X, y, Z, u, w, nthreads)
}

cpp_iv_product_completion <- function(XtX, Xty, X, y, U, w, nthreads) {
    .Call(`_fixest_cpp_iv_product_completion`, XtX, Xty, X, y, U, w, nthreads)
}

cpp_iv_resid <- function(resid_2nd, coef, resid_1st, is_int, nthreads) {
    .Call(`_fixest_cpp_iv_resid`, resid_2nd, coef, resid_1st, is_int, nthreads)
}

cpp_lgamma <- function(x) {
    .Call(`_fixest_cpp_lgamma`, x)
}

cpp_log_a_exp <- function(a, mu, exp_mu) {
    .Call(`_fixest_cpp_log_a_exp`, a, mu, exp_mu)
}

cpp_partialDerivative_other <- function(iterMax, Q, N, epsDeriv, ll_d2, dx_dother, init, dumMat, nbCluster) {
    .Call(`_fixest_cpp_partialDerivative_other`, iterMax, Q, N, epsDeriv, ll_d2, dx_dother, init, dumMat, nbCluster)
}

cpp_tapply_sum <- function(Q, x, dum) {
    .Call(`_fixest_cpp_tapply_sum`, Q, x, dum)
}

cpp_tapply_vsum <- function(Q, x, dum) {
    .Call(`_fixest_cpp_tapply_vsum`, Q, x, dum)
}

cpp_table <- function(Q, dum) {
    .Call(`_fixest_cpp_table`, Q, dum)
}

cpp_get_fe_gnl <- function(Q, N, sumFE, dumMat, cluster_sizes, obsCluster) {
    .Call(`_fixest_cpp_get_fe_gnl`, Q, N, sumFE, dumMat, cluster_sizes, obsCluster)
}

cpp_ssr_null <- function(y, w = numeric(0)) {
    .Call(`_fixest_cpp_ssr_null`, y, w)
}

cpp_ssq <- function(x, w = numeric(0)) {
    .Call(`_fixest_cpp_ssq`, x, w)
}

cpp_isConstant <- function(x) {
    .Call(`_fixest_cpp_isConstant`, x)
}

cpp_any_na_null <- function(x) {
    .Call(`_fixest_cpp_any_na_null`, x)
}

cpp_constant_dum <- function(k, x, dum, only_0 = FALSE) {
    .Call(`_fixest_cpp_constant_dum`, k, x, dum, only_0)
}

cpp_find_duplicates <- function(id, time) {
    .Call(`_fixest_cpp_find_duplicates`, id, time)
}

cpp_pgcd <- function(x) {
    .Call(`_fixest_cpp_pgcd`, x)
}

cpp_lag_obs <- function(id, time, nlag) {
    .Call(`_fixest_cpp_lag_obs`, id, time, nlag)
}

cpp_check_nested <- function(fe_list, cluster_list, fe_sizes, n) {
    .Call(`_fixest_cpp_check_nested`, fe_list, cluster_list, fe_sizes, n)
}

cpp_diag_XUtX <- function(X, U) {
    .Call(`_fixest_cpp_diag_XUtX`, X, U)
}

cpp_factor_matrix <- function(fact, is_na_all, who_is_dropped, var, col_names) {
    .Call(`_fixest_cpp_factor_matrix`, fact, is_na_all, who_is_dropped, var, col_names)
}

cpp_add_commas <- function(x, r = 1L, whole = TRUE) {
    .Call(`_fixest_cpp_add_commas`, x, r, whole)
}

cpp_find_never_always_treated <- function(cohort, period) {
    .Call(`_fixest_cpp_find_never_always_treated`, cohort, period)
}

cpp_get_first_item <- function(x, n_items) {
    .Call(`_fixest_cpp_get_first_item`, x, n_items)
}

cpp_combine_clusters <- function(cluster_list, index) {
    .Call(`_fixest_cpp_combine_clusters`, cluster_list, index)
}

cpp_get_nb_threads <- function() {
    .Call(`_fixest_cpp_get_nb_threads`)
}

cpppar_exp <- function(x, nthreads) {
    .Call(`_fixest_cpppar_exp`, x, nthreads)
}

cpppar_log <- function(x, nthreads) {
    .Call(`_fixest_cpppar_log`, x, nthreads)
}

cpppar_log_a_exp <- function(nthreads, a, mu, exp_mu) {
    .Call(`_fixest_cpppar_log_a_exp`, nthreads, a, mu, exp_mu)
}

cpppar_lgamma <- function(x, nthreads) {
    .Call(`_fixest_cpppar_lgamma`, x, nthreads)
}

cpppar_digamma <- function(x, nthreads) {
    .Call(`_fixest_cpppar_digamma`, x, nthreads)
}

cpppar_trigamma <- function(x, nthreads) {
    .Call(`_fixest_cpppar_trigamma`, x, nthreads)
}

cpppar_poisson_linkinv <- function(x, nthreads) {
    .Call(`_fixest_cpppar_poisson_linkinv`, x, nthreads)
}

cpppar_poisson_validmu <- function(x, nthreads) {
    .Call(`_fixest_cpppar_poisson_validmu`, x, nthreads)
}

cpppar_logit_linkfun <- function(x, nthreads) {
    .Call(`_fixest_cpppar_logit_linkfun`, x, nthreads)
}

cpppar_logit_linkinv <- function(x, nthreads) {
    .Call(`_fixest_cpppar_logit_linkinv`, x, nthreads)
}

cpppar_logit_mueta <- function(x, nthreads) {
    .Call(`_fixest_cpppar_logit_mueta`, x, nthreads)
}

cpppar_logit_devresids <- function(y, mu, wt, nthreads) {
    .Call(`_fixest_cpppar_logit_devresids`, y, mu, wt, nthreads)
}

cpppar_xwy <- function(X, y, w, nthreads) {
    .Call(`_fixest_cpppar_xwy`, X, y, w, nthreads)
}

cpppar_xbeta <- function(X, beta, nthreads) {
    .Call(`_fixest_cpppar_xbeta`, X, beta, nthreads)
}

cpppar_matprod <- function(x, y, nthreads) {
    .Call(`_fixest_cpppar_matprod`, x, y, nthreads)
}

cpppar_which_na_inf_vec <- function(x, nthreads) {
    .Call(`_fixest_cpppar_which_na_inf_vec`, x, nthreads)
}

cpppar_which_na_inf_mat <- function(mat, nthreads) {
    .Call(`_fixest_cpppar_which_na_inf_mat`, mat, nthreads)
}

cpppar_which_na_inf_df <- function(df, nthreads) {
    .Call(`_fixest_cpppar_which_na_inf_df`, df, nthreads)
}

cpppar_cond_means <- function(mat_vars, treat, nthreads = 1L) {
    .Call(`_fixest_cpppar_cond_means`, mat_vars, treat, nthreads)
}

cpppar_check_only_0 <- function(x_mat, nthreads) {
    .Call(`_fixest_cpppar_check_only_0`, x_mat, nthreads)
}

cpp_quf_gnl <- function(x) {
    .Call(`_fixest_cpp_quf_gnl`, x)
}

cpppar_quf_table_sum <- function(x, y, do_sum_y, rm_0, rm_1, rm_single, only_slope, nthreads, do_refactor, r_x_sizes, obs2keep) {
    .Call(`_fixest_cpppar_quf_table_sum`, x, y, do_sum_y, rm_0, rm_1, rm_single, only_slope, nthreads, do_refactor, r_x_sizes, obs2keep)
}

